server:
  port: 8989
  
spring:
  application:
    name: config-client
  cloud:
    bus: 
      trace:
        ## 开启消息跟踪
        enabled: true

#是否需要权限拉去，默认是true,如果不false就不允许你去拉取配置中心Server更新的内容
management:
  security:
    enabled: false
